version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
