version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-lock-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-lock-
      - run:
          name: Install JS
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-lock-{{ checksum "yarn.lock" }}
      - run:
          name: Test JS
          command: |
            yarn test